### PR TITLE
Joining and sidebar refresh on changes

### PR DESCRIPTION
**Pull request by DasGraMMa**
Joining a course now correctly knows whether the user is joined or not without needing to refresh the whole page (gets refreshed on navigating to the "Join Course" page).

Also, a small """hack""" has been introduced to keep the sidebar up to date on token refreshes.
The `AuthenticationService.tokenResponse` is now public and can be used in any `useEffect`-calls in React to react to token changes as the variable will get updated once `AutheticationService.refreshToken` is called.
Example for this is in the `DrawerContext.tsx#50`:
```ts
useEffect(() => {
    _getAllCourses();
}, [AuthenticationService.getInstance().tokenResponse]);
```
This refreshes the list of courses in the sidebar when a token refresh is called.

Whether this is good practice or not is to be discussed, but it works for now and a central way of checking token changes without much trouble and in a React-ish way, I guess.

### CODE REVIEW

**Comment by DasGraMMa** [comment]
Update: upon merging the current dev (which includes the my-courses endpoint) using it in the sidebar instead of the all-courses endpoints seems to mess up with the refresh of the sidebar.
I don't know why though, investigation is needed. Maybe refreshing the token happens faster than getting all the courses or something?

**Comment by DasGraMMa** [comment]
Update3: Everything should work now.

**Review by Nimeggis — APPROVED** [review]
approved
Edit: not approved ;)

**Comment by swjat** [comment]
After creating course and being redirected to course overview, the "Leave Course" button is visible for lecturer.

**Comment by DasGraMMa** [comment]
Update4: The details of the problem are described in the comment in the commit.
The token is being refreshed after creating the course, but apparently the changes are not propagated to the token fast enough, so the course role stays at `undefined`. Not sure how to really solve that though without a `sleep` or anything else blocking UI. Waiting between transition maybe? But even then, we are waiting for the creation and token refresh already.

**Comment by Nimeggis** [comment]
hab noch n button gechanged der veraltet war, weiß nicht ob der in deinem Ticket erstellt wurde, jedenfalls hab ich das kurz gefixed in deinem Branch

**Review by swjat — APPROVED** [review]
approved
(and I saw what you did to complexity +1)

**Pull request merged**
